name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
      - name: Delete old backend docker container
        run: sudo docker rm -f cicd-pipeline-progmasters-2023-blog-2-backend || true
      - name: Delete old frontend docker container
        run: sudo docker rm -f cicd-pipeline-progmasters-2023-blog-2-frontend || true
      - name: Delete all docker image
        run: sudo docker image prune -a -f

      - name: Pull backend docker image
        run: sudo docker pull kleskaakos/cicd-pipeline-progmasters-2023-blog-2-backend:latest
      - name: Run backend docker container
        run: sudo docker run -d -p 9000:9000 --name cicd-pipeline-progmasters-2023-blog-2-backend kleskaakos/cicd-pipeline-progmasters-2023-blog-2-backend

      - name: Pull frontend docker image
        run: sudo docker pull kleskaakos/cicd-pipeline-progmasters-2023-blog-2-frontend:latest
      - name: Run frontend docker container
        run: sudo docker run -d -p 80:80 --name cicd-pipeline-progmasters-2023-blog-2-frontend kleskaakos/cicd-pipeline-progmasters-2023-blog-2-frontend
